### ISSUE TITLE
Is this functional yet?

### ISSUE THREAD

**Issue by SlayerOfTheBad** [VirtualZer0/IsaacOnTwitchReloaded-site#3]
We've been trying to set this up for the past 5 hours and whilst we've made some headway, the whole system doesn't seem to do anything yet? The local site connects up properly with Twitch and with Binding of Isaac, but never seems to complete the connection with the game, and forcefully calling isaacConnect::connect() definitely didn't work.

So we're wondering whether this project is in a useable state or whether it's still a WIP?

**Comment by VirtualZer0** [comment]
Hello. Yes, it's still WIP. Hopefully I can add functionality from the old mod in mid-August. You can check the release tab here from time to time to find out when the first playable version is out.
